### ISSUE TITLE
Error while executing consistency check

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#13]
When I call `/api/theories/5c3b1516c20c9c26b9b0d0c6/consistency`, the back end server crashes with

```
/home/lex/dev/nai/backend/models/queryHelper.js:4
    cb(mtch[1],mtch[2]);
           ^

TypeError: Cannot read property '1' of null
    at Function.parse (/home/lex/dev/nai/backend/models/queryHelper.js:4:12)
    at execFile (/home/lex/dev/nai/backend/models/queryHelper.js:11:19)
    at ChildProcess.exithandler (child_process.js:268:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lex/.npm/_logs/2019-01-13T12_26_19_674Z-debug.log
```

Any ideas?

**Comment by shaolintl** [comment]
I guess there are errors in the format which prevents mleancop from reading it and the output is therefore not the standard one, which prevents me from pattern matching. I will catch such errors and return them.
