### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by shaolintl** [normativeai/backend#16]
0|www      |     at /opt/nai-backend/controllers/queryController.js:91:29
0|www      |     at Function.parse (/opt/nai-backend/models/queryHelper.js:5:7)
0|www      |     at execFile (/opt/nai-backend/models/queryHelper.js:15:19)
0|www      |     at ChildProcess.exithandler (child_process.js:267:7)
0|www      |     at emitTwo (events.js:126:13)
0|www      |     at ChildProcess.emit (events.js:214:7)

**Comment by shaolintl** [comment]
The above was fixed.
