### ISSUE TITLE
Spurious server crash

### ISSUE THREAD

**Issue by lex-lex** [normativeai/backend#17]
Just got a server crash; I am not sure why though. Log file is attached.
[2019-02-12T14_47_29_775Z-debug.log](https://github.com/normativeai/backend/files/2856328/2019-02-12T14_47_29_775Z-debug.log)

```
....
GET /api/queries/5c62dc4ecff6be5fb88d89bd/exec 400 5023.186 ms - 39
PUT /api/queries/5c62dc4ecff6be5fb88d89bd 200 3.098 ms - 27
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/lex/dev/nai/backend/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/lex/dev/nai/backend/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/lex/dev/nai/backend/node_modules/express/lib/response.js:267:15)
    at /home/lex/dev/nai/backend/controllers/queryController.js:91:29
    at Function.parse (/home/lex/dev/nai/backend/models/queryHelper.js:5:7)
    at execFile (/home/lex/dev/nai/backend/models/queryHelper.js:15:19)
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lex/.npm/_logs/2019-02-12T14_47_29_775Z-debug.log
```

**Comment by lex-lex** [comment]
(Spurious because I think server headers should be handled by some library and this might not be an error of the backend?)
